### ISSUE TITLE
Freeze with no BAR TT and MagicMenu 2.35

### ISSUE THREAD

**Issue by EctoOne** [RasmusEdgar/dintwm#6] opened 2022-01-27 00:17 UTC
Hi, I found this on Aminet before and noticed the update today.

I had issues before but I didn't really looked into it but with a newer update I thought I give it another try.

The first thing I noticed is that it is somehow incompatible with MagicMenu, I'm using version 2.35 from Aminet. My system freezes when I right click to open any WB menu.

The second issue is that when I remove the BAR=true tooltype, my systems freezes whenever I start dintwm. Even when I boot from a normal WB 3.1 disk.

I hope this can be fixed because I'm really looking forward to try it out further. It seems like a really good idea, since opening a drawer opens a new window.

Edit: Oh, I forgot that the included text file contains some special characters so I couldn't open it with MultiView or the DirOpus4 reader. I removed them with GoldED and then it worked fine.

**Comment by RasmusEdgar** [comment] 2022-01-27 15:03
Hi EctoOne,
Thanks for the bug report.

From the bottom up.
The special characters in the text was document was caused by pandoc doing "smart" conversion of quotation marks. Thanks  for catching that one. It has now been fixed and will be released in the next update.

Concerning the freeze problem when disabling BAR TT - I can't seem to replicate it with my own 3.1 setup, but I'll try to replicate it during the next couple of days.

The problem with MagicMenu and Dintwm is easily replicated though, and I'll look into what is causing the problem.

**Comment by EctoOne** [comment] 2022-01-27 16:21
Thanks for looking into this. Maybe I should mention that I'm using uae4arm to emulate my system. Maybe I have a weird config, I will also try some different settings and see if I can find a working configuration.

As for MagicMenu, there is a package called ObtainGIRPort.lha available on Aminet, which apparently fixes deadlock situations. Whatever that means. I never encountered a problem with MagicMenu before but I tried it and it didn't help in this case. Maybe it was for an older version.

**Comment by EctoOne** [comment] 2022-01-28 03:02
I narrowed it down a bit. In uae4arm there is a CPU setting called 24-bit addressing available for the 68020 processor which needs to be enabled. In my setup I'm using a 68030 which auto disables this setting.

But I also noticed another issue while trying things out. Without the BAR TT, only the window which contains your program will be maxed. When I open a drawer, it opens normally and does not get tiled. When I add the BAR TT it works fine.

When I use this setting on my main setup I'm getting all kinds of errors from different programs. It won't even make it through the whole boot process.

**Comment by RasmusEdgar** [comment] 2022-01-28 14:08
Yep. Loads of bugs around BAR TT it seems. Will have a deep look at it and test thoroughly. Thanks.

**Comment by RasmusEdgar** [comment] 2022-04-11 13:13
Hi EctoOne,
Can you test:
https://github.com/RasmusEdgar/dintwm/releases/download/v0.6-rc1/dintwm.lha
regarding the BAR TT issue, which I believe was due to some missing checks.
Also please try to disable "Non Blocking" in MagicMenu prefs and see if that helps with the dead lock. It seems to viable workaround for me.

**Comment by EctoOne** [comment] 2022-04-24 04:05
I just tried it for a few minutes and can confirm that it does work when I disable "Non Blocking".

But I noticed some issues with my DOpus4 config. I'm starting it from a Dock, and sometimes I start it again instead of switching to its screen. This brings up a requester with some options and that requester currently causes a freeze. Same with opening SwazInfo within DOpus4.

**Comment by RasmusEdgar** [comment] 2022-04-24 09:13
Thanks for finding more bugs. It would be helpful if we can find a way to share the hdf image you are using, because I can not replicate the problem on my installation neither with Swazinfo or with DOpus4. Perhaps you can share it through something like wetransfer and you can use this email: edgarmayn\<the a like char with a whirl\>protonmail.com

**Comment by EctoOne** [comment] 2022-04-25 03:06
Before I share my hdf, I would prefer it to narrow down the problem first. Maybe it's another conflict with one of the other tool's in my setup, but I currently don't have much time.

**Comment by EctoOne** [comment] 2022-05-05 02:35
So I finally had some time to mess around with the new version but I wasn't able to narrow down the source of the problems with DOpus4. And to be honest, I actually don't care that much. It's a great tool but I just don't see me using it regularly. And as much as I would like to help, I'm not going to share my hdf, sorry.

**Comment by RasmusEdgar** [comment] 2022-05-05 07:52
That is perfectly fine. Thanks for the time spent on locating the bugs. Closing.

**Closed as completed by RasmusEdgar** 2022-05-05 07:52 UTC
